apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-server
spec:
  # serviceName: mysql-service
  selector:
    matchLabels:
      app: mysql-pod
  template:
    metadata:
      labels:
        app: mysql-pod
    spec:
      containers:
      - image: mysql:latest
        name: mysql-container
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: common-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: common-secret
              key: MYSQL_USERNAME
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-server-pv-claim